function setweboptions(T)
% called when changing User, Password or Timeout
    T.Options=weboptions('Username',T.User,'Password',T.Password,...
        'Timeout',T.Timeout,...
        'HeaderFields',{'Authorization', ...
        ['Basic ' matlab.net.base64encode([T.User ':' T.Password])]});
